### ISSUE TITLE
token merging/tome patch error

### ISSUE THREAD

**Issue by Mystic419** [dbolya/tomesd#34] opened 2023-05-05 06:34 UTC
Kind of new to this but i tried to install to an existing install of stable diffusion and i got this error:
Failed to apply ToMe patch, continuing as normal module 'tomesd' has no attribute 'apply_patch'

no matter what i did would not fix the problem so i did a fresh install of SD and now i get:

Exception thrown when removing ToMe patch, continuing as normal module 'tomesd' has no attribute 'remove_patch'

this is all coming from the webui-user.bat window.

How can I fix this in either install, I kept the original as a backup...

i did the fallowing in both installs:

1.  ran vent\scripts\.\activate in powershell
2. CD out to SD directory and run:
git clone https://github.com/dbolya/tomesd
cd tomesd
python setup.py build develop
each separately with no errors
3. run webui-user.bat and i get the above error according to the install

**Comment by Mystic419** [comment] 2023-05-05 07:16
Not sure what i did but i got it to work. if others have same problem i will try to hepl walk you throught it.

**Comment by dbolya** [comment] 2023-05-07 21:00
Seems like a duplicate of #33. This happens when you install the package in the wrong python environment.  
Glad you were able to get it to work, though!

**Closed by dbolya** 2023-05-07 21:00 UTC
